PUT localhost:8088/employee
Content-Type: application/json

{
    "departmentId": "1",
    "employee": {
        "name": "abc",
         "surname": "b",
         "bornDate": "343445",
         "residency": "d",
         "role": "TIMEKEEPER",
         "days": []
    }
}